# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1eacf48a72410e2b6ba7986c2eb183538c1106aa1864d1d6af257556e2fecde1a85d7025fde401cc4a4ec81fe35fcc56d9ca2f447b5a2dd051606c747eac286

test:
  secret_key_base: a5c805b4facdd617613178b64cea9bc8d04b56aa8abac818900ea9163de2c8ab35056dab4f55d235cbf4fac581eedb781aaffb176f911d06afda1a2fdcfe3c78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
